basePath: /
host: localhost:5000
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is a simple real estate management service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rielz API
  version: "1.0"
paths:
  /api/houses:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All Houses
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Create House for landlord
  /api/houses/id:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Delete house By Landlord
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All Houses By Id
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Update Houses By Landlord
  /api/houses/landlord:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All Houses By Landlord
  /api/houses/landlord/id:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All Houses By Landlord
  /api/houses/state:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All Houses By state
  /api/houses/tenant:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Add Tenant By Landlord
  /api/users:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All landlords
  /api/users/id:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get All landlords
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Update landlords
  /login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Login for landlords
  /signup:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Registration for landlords
swagger: "2.0"
